from .get_new_object_repair_group_adapter import GetNewObjectRepairGroupAdapter
from .get_new_tech_position_adapter import GetNewTechPositionAdapter
from .get_new_equipment_adapter import GetNewEquipmentAdapter
